numStr1, numStr2 = input().split()
print(int(numStr1) + int(numStr2))
print(int(numStr1) - int(numStr2))
print(int(numStr1) * int(numStr2))
print(int(int(numStr1) / int(numStr2)))
print(int(numStr1) % int(numStr2))